export class Mission {
	constructor(
		public id: number,
		public isActive: boolean,
		public isEmergency: boolean,
		public title: string,
		public description: string,
		public dateStart: Date,
		public dateEnd: Date,
		public alarms: Alarm[],
		public meetingPoint: string, // geolocation { lat, lng }
		public meetingPointNicename: string, // converted geolocation to nicename
		public creator: SARUser,
		public expences: Expence[],
		public missionResponses : MissionResponse[]
	) { }
}

export class Alarm {

	constructor(
		public id?: number,
		public date?: Date, // datestamp at creation
		public message?: string,
		public mission?: Mission,
		public persons?: SARUser[] // Persons to be alarmed
	) { }

}


export class SARUser {

	constructor(
		public id: number,
		public hasApp: boolean,
		public isAdmin: boolean,
		public email: string,
		public phone: number,
		public name: string,
		public organization: string,
		public isAvailable: boolean,
		public isTrackable: boolean,
		public checked : boolean, // bool used for checking peoplelist (not persisted)
		public access_token : string
	) { }

}

export class Expence {
	constructor(
		public id: number,
		public title: string,
		public description: string,
		public amount: number,
		public mission: Mission,
		public person: SARUser
	) { }
}

export class MissionResponse {
	constructor(
		public alarm: Alarm,
		public person: SARUser,
		public response: boolean,
		public date: number,  // Autogenerated time of respons
		public comment: string,
		public trackings: Tracking[] // If user has tracking enable
	) { }
}

export class Tracking {
	constructor(
		public missionresponse: MissionResponse,
		public positionLat: string,
		public positionLong: string,
		public date: number
	) { }
}