export class Mission {
	constructor(
		public id: number,
		public isActive: boolean,
		public isEmergency: boolean,
		public title: string,
		public description: string,
		public dateStart: Date,
		public dateEnd: Date,
		public alarms: Alarm[],
		public meetingPoint: any, // geolocation { lat, lng }
		public meetingPointNicename: string, // converted geolocation to nicename
		public creator: SARUser,
		public expences: Expence[],
		public missionResponses : MissionResponse[]
	) { }
}

export class Alarm {

	constructor(
		public id?: number,
		public date?: Date, // datestamp at creation
		public message?: string,
		public mission?: Mission,
		public persons?: SARUser[] // Persons to be alarmed
	) { }
}


export class SARUser {
	constructor(
		public id: number,
		public hasApp: boolean,
		public isAdmin: boolean,
		public email: string,
		public phone: number,
		public name: string,
		public organization: string,
		public isAvailable: boolean,
		public isTrackable: boolean,
		public checked : boolean, // bool used for checking peoplelist (not persisted)
		public access_token : string,
		public deviceToken : string,
	) { }
}

export class Expence {
	constructor(
		public id: number,
		public title: string,
		public description: string,
		public amount: number,
		public missionId: number,
		public sARUserId: number
	) { }
}

export class MissionResponse {
	constructor(
		public id: number,
		public missionId: number,
		public saruserId: number,
		public response: boolean,
		public date: Date,  // Autogenerated time of respons
		public comment: string,
		public trackings: Tracking // If user has tracking enable
	) { }
}

export class Tracking {
	constructor(
		public date: Date,
		public geopoint: any,
		public id: number,
		public missionResponseId: number,
	) {}
}

export class AlarmResponse {
	constructor(
		public id: number,
		public sarUserId: number,
		public alarmId: number,
		public missionId: number,
		public alarm: Alarm,
	) {}
}
